"""initial schema

Baseline squash of the original 19 migrations into a single initial revision.
The schema below is the exact DDL produced by running those migrations against
a fresh PostgreSQL 17 database (verified byte-identical via pg_dump diff).
Embedded as raw SQL rather than autogenerated ops because several
performance-critical indexes (trigram/BRIN/functional) and server-side
defaults were added via raw SQL and are not present in the ORM metadata.

Revision ID: 3ae9e0afdc49
Revises:
Create Date: 2026-06-15 15:15:18.459231

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3ae9e0afdc49"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


SCHEMA_SQL = r"""
CREATE EXTENSION IF NOT EXISTS pg_stat_statements WITH SCHEMA public;
CREATE EXTENSION IF NOT EXISTS pg_trgm WITH SCHEMA public;
CREATE TYPE public.importoutcome AS ENUM (
    'pending',
    'imported',
    'failed_no_match',
    'failed_io',
    'ambiguous'
);
CREATE TYPE public.quality AS ENUM (
    'uhd',
    'fullhd',
    'hd',
    'sd',
    'unknown'
);
CREATE TYPE public.torrentstatus AS ENUM (
    'finished',
    'downloading',
    'paused',
    'error',
    'unknown'
);
CREATE TABLE public.activity_log (
    id uuid NOT NULL,
    "timestamp" timestamp with time zone DEFAULT now() NOT NULL,
    level character varying(10) NOT NULL,
    module character varying(255) NOT NULL,
    message text NOT NULL,
    correlation_id character varying(36),
    extra jsonb
);
CREATE TABLE public.episode (
    id uuid NOT NULL,
    season_id uuid NOT NULL,
    number integer NOT NULL,
    title character varying NOT NULL,
    overview character varying,
    skipped boolean NOT NULL,
    air_date date,
    downloaded boolean DEFAULT false NOT NULL
);
CREATE TABLE public.episode_file (
    episode_id uuid NOT NULL,
    torrent_id uuid,
    quality public.quality NOT NULL,
    variant character varying NOT NULL,
    import_status public.importoutcome NOT NULL,
    import_error character varying,
    imported_at timestamp with time zone,
    last_attempt_at timestamp with time zone,
    attempt_count integer NOT NULL,
    sha1 character varying,
    id uuid NOT NULL,
    codec character varying NOT NULL,
    hdr boolean NOT NULL,
    source character varying NOT NULL,
    extra character varying NOT NULL
);
CREATE TABLE public.ignored_import_path (
    id uuid NOT NULL,
    path text NOT NULL,
    created_at timestamp with time zone NOT NULL
);
CREATE TABLE public.import_batch (
    id character varying(16) NOT NULL,
    total integer DEFAULT 0 NOT NULL,
    CONSTRAINT import_batch_singleton CHECK (((id)::text = 'current'::text))
);
CREATE TABLE public.import_queue_item (
    id uuid NOT NULL,
    kind character varying(16) NOT NULL,
    ref_id text NOT NULL,
    tab character varying(16) NOT NULL,
    sort_at timestamp with time zone NOT NULL,
    payload jsonb NOT NULL
);
CREATE TABLE public.indexer_query_result (
    id uuid NOT NULL,
    title character varying NOT NULL,
    download_url character varying NOT NULL,
    seeders integer NOT NULL,
    quality public.quality NOT NULL,
    usenet boolean NOT NULL,
    age integer NOT NULL,
    flags character varying[],
    season integer[],
    episode integer[],
    size bigint,
    score integer NOT NULL,
    indexer character varying,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);
CREATE TABLE public.indexer_site (
    id uuid NOT NULL,
    name character varying NOT NULL,
    site_type character varying(20) NOT NULL,
    url character varying NOT NULL,
    available_urls character varying[] NOT NULL,
    api_key character varying NOT NULL,
    supports_tv boolean NOT NULL,
    supports_movies boolean NOT NULL,
    categories_tv character varying NOT NULL,
    categories_movies character varying NOT NULL,
    cloudflare_protected boolean NOT NULL,
    enabled boolean NOT NULL,
    is_preloaded boolean NOT NULL,
    priority integer DEFAULT 100 NOT NULL,
    last_success_at timestamp with time zone,
    last_test_status character varying(20),
    last_test_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);
CREATE TABLE public.manual_parse_token (
    id uuid NOT NULL,
    payload jsonb NOT NULL,
    created_at timestamp with time zone NOT NULL
);
CREATE TABLE public.media_file_inventory (
    id uuid NOT NULL,
    file_id uuid NOT NULL,
    media_type character varying DEFAULT ''::character varying NOT NULL,
    kind character varying DEFAULT 'video'::character varying NOT NULL,
    language character varying DEFAULT ''::character varying NOT NULL,
    path character varying NOT NULL,
    size_bytes bigint DEFAULT '0'::bigint NOT NULL,
    mtime_ns bigint DEFAULT '0'::bigint NOT NULL,
    last_seen_at timestamp with time zone DEFAULT now() NOT NULL
);
CREATE TABLE public.media_request (
    id uuid NOT NULL,
    media_type character varying(10) NOT NULL,
    title character varying NOT NULL,
    external_id character varying NOT NULL,
    imdb_id character varying,
    metadata_provider character varying NOT NULL,
    movie_id uuid,
    show_id uuid,
    season_number integer,
    status character varying(20) NOT NULL,
    wanted_quality integer,
    requested_by_id uuid,
    decided_by_id uuid,
    note character varying,
    source character varying(10) DEFAULT 'native'::character varying NOT NULL,
    tmdb_id integer,
    seerr_request_id integer,
    seerr_media_id integer,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT media_request_media_type_valid CHECK (((media_type)::text = ANY ((ARRAY['movie'::character varying, 'show'::character varying])::text[]))),
    CONSTRAINT media_request_source_valid CHECK (((source)::text = ANY ((ARRAY['native'::character varying, 'seerr'::character varying])::text[]))),
    CONSTRAINT media_request_status_valid CHECK (((status)::text = ANY ((ARRAY['pending'::character varying, 'approved'::character varying, 'downloading'::character varying, 'downloaded'::character varying, 'rejected'::character varying])::text[]))),
    CONSTRAINT media_request_type_matches_fk CHECK (((((media_type)::text = 'movie'::text) AND (show_id IS NULL)) OR (((media_type)::text = 'show'::text) AND (movie_id IS NULL))))
);
CREATE TABLE public.movie (
    id uuid NOT NULL,
    external_id character varying NOT NULL,
    metadata_provider character varying NOT NULL,
    name character varying NOT NULL,
    overview character varying NOT NULL,
    year integer,
    library character varying NOT NULL,
    original_language character varying,
    imdb_id character varying,
    continuous_download boolean,
    skipped boolean NOT NULL,
    vote_average double precision,
    content_rating character varying,
    runtime integer,
    genres jsonb,
    "cast" jsonb,
    preferred_quality jsonb,
    preferred_codec jsonb,
    subtitle_languages jsonb,
    last_metadata_check timestamp with time zone,
    release_date date,
    auto_download_backoff_until timestamp with time zone,
    downloaded boolean DEFAULT false NOT NULL,
    metadata_failure_backoff_until timestamp with time zone
);
CREATE TABLE public.movie_file (
    movie_id uuid NOT NULL,
    quality public.quality NOT NULL,
    variant character varying NOT NULL,
    torrent_id uuid,
    import_status public.importoutcome NOT NULL,
    import_error character varying,
    imported_at timestamp with time zone,
    last_attempt_at timestamp with time zone,
    attempt_count integer NOT NULL,
    sha1 character varying,
    id uuid NOT NULL,
    codec character varying NOT NULL,
    hdr boolean NOT NULL,
    source character varying NOT NULL,
    extra character varying NOT NULL
);
CREATE TABLE public.notification (
    id uuid NOT NULL,
    message character varying NOT NULL,
    read boolean NOT NULL,
    "timestamp" timestamp with time zone NOT NULL
);
CREATE TABLE public.oauth_account (
    access_token character varying(4096) NOT NULL,
    refresh_token character varying(4096),
    id uuid NOT NULL,
    user_id uuid NOT NULL,
    oauth_name character varying(100) NOT NULL,
    expires_at integer,
    account_id character varying(320) NOT NULL,
    account_email character varying(320) NOT NULL
);
CREATE TABLE public.scan_result_cache (
    id uuid NOT NULL,
    directory text NOT NULL,
    payload jsonb NOT NULL,
    scanned_at timestamp with time zone NOT NULL
);
CREATE TABLE public.scan_run (
    id character varying(16) NOT NULL,
    state character varying(16) NOT NULL,
    started_at timestamp with time zone,
    finished_at timestamp with time zone,
    items_found integer NOT NULL,
    last_error text,
    CONSTRAINT scan_run_singleton CHECK (((id)::text = 'current'::text))
);
CREATE TABLE public.season (
    id uuid NOT NULL,
    show_id uuid NOT NULL,
    number integer NOT NULL,
    skipped boolean NOT NULL
);
CREATE TABLE public.show (
    id uuid NOT NULL,
    external_id character varying NOT NULL,
    metadata_provider character varying NOT NULL,
    name character varying NOT NULL,
    overview character varying NOT NULL,
    year integer,
    ended boolean NOT NULL,
    continuous_download boolean,
    library character varying NOT NULL,
    original_language character varying,
    imdb_id character varying,
    preferred_quality jsonb,
    preferred_codec jsonb,
    subtitle_languages jsonb,
    skipped boolean NOT NULL,
    vote_average double precision,
    content_rating character varying,
    genres jsonb,
    "cast" jsonb,
    last_metadata_check timestamp with time zone,
    auto_download_backoff_until timestamp with time zone,
    wanted_episode_count integer DEFAULT 0 NOT NULL,
    downloaded_episode_count integer DEFAULT 0 NOT NULL,
    list_progress_status character varying(16) DEFAULT 'none'::character varying NOT NULL,
    metadata_failure_backoff_until timestamp with time zone
);
CREATE TABLE public.subtitle_record (
    id uuid NOT NULL,
    media_type character varying NOT NULL,
    episode_id uuid,
    movie_id uuid,
    language character varying NOT NULL,
    source character varying NOT NULL,
    provider character varying,
    downloaded_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT subtitle_record_episode_xor_movie CHECK (((episode_id IS NULL) <> (movie_id IS NULL)))
);
CREATE TABLE public.system_config_override (
    id integer NOT NULL,
    overrides jsonb NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT system_config_override_singleton CHECK ((id = 1))
);
CREATE SEQUENCE public.system_config_override_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;
ALTER SEQUENCE public.system_config_override_id_seq OWNED BY public.system_config_override.id;
CREATE TABLE public.torrent (
    id uuid NOT NULL,
    status public.torrentstatus NOT NULL,
    title character varying NOT NULL,
    quality public.quality NOT NULL,
    hash character varying(40) NOT NULL,
    usenet boolean NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT torrent_hash_length CHECK ((length((hash)::text) = 40))
);
CREATE TABLE public.torrent_block (
    info_hash character varying(40) NOT NULL,
    title text,
    reason text DEFAULT 'no_video_files'::text NOT NULL,
    blocked_at timestamp with time zone DEFAULT now() NOT NULL
);
CREATE TABLE public.torrent_history (
    id uuid NOT NULL,
    torrent_id uuid,
    info_hash character varying(40),
    title text NOT NULL,
    quality public.quality NOT NULL,
    usenet boolean DEFAULT false NOT NULL,
    media_type character varying,
    media_id uuid,
    media_name text,
    media_year integer,
    outcome character varying DEFAULT 'downloaded'::character varying NOT NULL,
    files jsonb DEFAULT '[]'::jsonb NOT NULL,
    files_total integer DEFAULT 0 NOT NULL,
    files_imported integer DEFAULT 0 NOT NULL,
    import_error text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    imported_at timestamp with time zone,
    removed_at timestamp with time zone
);
CREATE TABLE public."user" (
    last_login_at timestamp with time zone,
    id uuid NOT NULL,
    email character varying(320) NOT NULL,
    hashed_password character varying(1024) NOT NULL,
    is_active boolean NOT NULL,
    is_superuser boolean NOT NULL,
    is_verified boolean NOT NULL
);
CREATE TABLE public.user_api_tokens (
    id uuid NOT NULL,
    user_id uuid NOT NULL,
    name character varying(120) NOT NULL,
    token_hash character varying(64) NOT NULL,
    preview character varying(16) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    last_used_at timestamp with time zone,
    expires_at timestamp with time zone
);
ALTER TABLE ONLY public.system_config_override ALTER COLUMN id SET DEFAULT nextval('public.system_config_override_id_seq'::regclass);
ALTER TABLE ONLY public.activity_log
    ADD CONSTRAINT activity_log_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.torrent_block
    ADD CONSTRAINT blocked_torrent_hash_pkey PRIMARY KEY (info_hash);
ALTER TABLE ONLY public.episode_file
    ADD CONSTRAINT episode_file_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.episode
    ADD CONSTRAINT episode_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.episode
    ADD CONSTRAINT episode_season_id_number_key UNIQUE (season_id, number);
ALTER TABLE ONLY public.ignored_import_path
    ADD CONSTRAINT ignored_import_path_path_key UNIQUE (path);
ALTER TABLE ONLY public.ignored_import_path
    ADD CONSTRAINT ignored_import_path_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.import_batch
    ADD CONSTRAINT import_batch_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.import_queue_item
    ADD CONSTRAINT import_queue_item_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.indexer_query_result
    ADD CONSTRAINT indexer_query_result_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.indexer_site
    ADD CONSTRAINT indexer_site_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.manual_parse_token
    ADD CONSTRAINT manual_parse_token_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.media_file_inventory
    ADD CONSTRAINT media_file_inventory_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.media_request
    ADD CONSTRAINT media_request_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.movie
    ADD CONSTRAINT movie_external_id_metadata_provider_key UNIQUE (external_id, metadata_provider);
ALTER TABLE ONLY public.movie_file
    ADD CONSTRAINT movie_file_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.movie
    ADD CONSTRAINT movie_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.notification
    ADD CONSTRAINT notification_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.oauth_account
    ADD CONSTRAINT oauth_account_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.scan_result_cache
    ADD CONSTRAINT scan_result_cache_directory_key UNIQUE (directory);
ALTER TABLE ONLY public.scan_result_cache
    ADD CONSTRAINT scan_result_cache_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.scan_run
    ADD CONSTRAINT scan_run_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.season
    ADD CONSTRAINT season_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.season
    ADD CONSTRAINT season_show_id_number_key UNIQUE (show_id, number);
ALTER TABLE ONLY public.show
    ADD CONSTRAINT show_external_id_metadata_provider_key UNIQUE (external_id, metadata_provider);
ALTER TABLE ONLY public.show
    ADD CONSTRAINT show_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.subtitle_record
    ADD CONSTRAINT subtitle_record_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.system_config_override
    ADD CONSTRAINT system_config_override_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.torrent
    ADD CONSTRAINT torrent_hash_key UNIQUE (hash);
ALTER TABLE ONLY public.torrent_history
    ADD CONSTRAINT torrent_history_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.torrent
    ADD CONSTRAINT torrent_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.episode_file
    ADD CONSTRAINT uq_episode_file_naming UNIQUE (episode_id, quality, codec, variant, extra);
ALTER TABLE ONLY public.import_queue_item
    ADD CONSTRAINT uq_import_queue_item_ref UNIQUE (kind, ref_id, tab);
ALTER TABLE ONLY public.media_file_inventory
    ADD CONSTRAINT uq_media_file_inventory_lookup UNIQUE (file_id, kind, language);
ALTER TABLE ONLY public.movie_file
    ADD CONSTRAINT uq_movie_file_naming UNIQUE (movie_id, quality, codec, variant, extra);
ALTER TABLE ONLY public.user_api_tokens
    ADD CONSTRAINT user_api_tokens_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public."user"
    ADD CONSTRAINT user_pkey PRIMARY KEY (id);
CREATE INDEX idx_indexer_query_result_score_seeders ON public.indexer_query_result USING btree (score DESC, seeders DESC);
CREATE INDEX ix_activity_log_level ON public.activity_log USING btree (level);
CREATE INDEX ix_activity_log_module ON public.activity_log USING btree (module);
CREATE INDEX ix_activity_log_timestamp ON public.activity_log USING btree ("timestamp");
CREATE INDEX ix_activity_log_timestamp_brin ON public.activity_log USING brin ("timestamp");
CREATE INDEX ix_blocked_torrent_hash_lower ON public.torrent_block USING btree (lower((info_hash)::text));
CREATE INDEX ix_episode_downloaded ON public.episode USING btree (downloaded);
CREATE INDEX ix_episode_file_episode_id ON public.episode_file USING btree (episode_id);
CREATE INDEX ix_episode_file_import_status ON public.episode_file USING btree (import_status);
CREATE INDEX ix_episode_file_import_status_pending ON public.episode_file USING btree (import_status) WHERE (import_status <> 'imported'::public.importoutcome);
CREATE INDEX ix_episode_file_sha1_pending ON public.episode_file USING btree (episode_id) WHERE ((sha1 IS NULL) AND (import_status = 'imported'::public.importoutcome));
CREATE INDEX ix_episode_file_torrent_id ON public.episode_file USING btree (torrent_id);
CREATE INDEX ix_episode_season_id ON public.episode USING btree (season_id);
CREATE INDEX ix_episode_skipped ON public.episode USING btree (skipped);
CREATE INDEX ix_import_queue_item_tab_sort ON public.import_queue_item USING btree (tab, sort_at);
CREATE INDEX ix_indexer_query_result_created_at ON public.indexer_query_result USING btree (created_at);
CREATE INDEX ix_manual_parse_token_created_at ON public.manual_parse_token USING btree (created_at);
CREATE INDEX ix_media_file_inventory_lookup ON public.media_file_inventory USING btree (file_id, kind, language);
CREATE UNIQUE INDEX ix_media_file_inventory_path ON public.media_file_inventory USING btree (path);
CREATE INDEX ix_media_request_decided_by_id ON public.media_request USING btree (decided_by_id);
CREATE INDEX ix_media_request_movie_id ON public.media_request USING btree (movie_id);
CREATE INDEX ix_media_request_requested_by_id ON public.media_request USING btree (requested_by_id);
CREATE INDEX ix_media_request_show_id ON public.media_request USING btree (show_id);
CREATE INDEX ix_media_request_status ON public.media_request USING btree (status);
CREATE INDEX ix_media_request_status_media_type ON public.media_request USING btree (status, media_type);
CREATE INDEX ix_movie_auto_download_backoff ON public.movie USING btree (auto_download_backoff_until) WHERE (auto_download_backoff_until IS NOT NULL);
CREATE INDEX ix_movie_downloaded ON public.movie USING btree (downloaded);
CREATE INDEX ix_movie_file_import_status ON public.movie_file USING btree (import_status);
CREATE INDEX ix_movie_file_import_status_pending ON public.movie_file USING btree (import_status) WHERE (import_status <> 'imported'::public.importoutcome);
CREATE INDEX ix_movie_file_movie_id ON public.movie_file USING btree (movie_id);
CREATE INDEX ix_movie_file_sha1_pending ON public.movie_file USING btree (movie_id) WHERE ((sha1 IS NULL) AND (import_status = 'imported'::public.importoutcome));
CREATE INDEX ix_movie_file_torrent_id ON public.movie_file USING btree (torrent_id);
CREATE INDEX ix_movie_library_name ON public.movie USING btree (library, name);
CREATE INDEX ix_movie_metadata_failure_backoff ON public.movie USING btree (metadata_failure_backoff_until) WHERE (metadata_failure_backoff_until IS NOT NULL);
CREATE INDEX ix_movie_name_trgm ON public.movie USING gin (name public.gin_trgm_ops);
CREATE INDEX ix_movie_skipped ON public.movie USING btree (skipped);
CREATE INDEX ix_notification_timestamp ON public.notification USING btree ("timestamp" DESC);
CREATE INDEX ix_notification_unread ON public.notification USING btree ("timestamp") WHERE (read = false);
CREATE INDEX ix_oauth_account_account_id ON public.oauth_account USING btree (account_id);
CREATE INDEX ix_oauth_account_oauth_name ON public.oauth_account USING btree (oauth_name);
CREATE INDEX ix_oauth_account_user_id ON public.oauth_account USING btree (user_id);
CREATE INDEX ix_scan_result_cache_payload_status ON public.scan_result_cache USING btree (((payload ->> 'status'::text)));
CREATE INDEX ix_season_show_id ON public.season USING btree (show_id);
CREATE INDEX ix_season_skipped ON public.season USING btree (skipped);
CREATE INDEX ix_show_auto_download_backoff ON public.show USING btree (auto_download_backoff_until) WHERE (auto_download_backoff_until IS NOT NULL);
CREATE INDEX ix_show_imdb_id ON public.show USING btree (imdb_id);
CREATE INDEX ix_show_library_name ON public.show USING btree (library, name);
CREATE INDEX ix_show_list_progress_status ON public.show USING btree (list_progress_status);
CREATE INDEX ix_show_metadata_failure_backoff ON public.show USING btree (metadata_failure_backoff_until) WHERE (metadata_failure_backoff_until IS NOT NULL);
CREATE INDEX ix_show_name_trgm ON public.show USING gin (name public.gin_trgm_ops);
CREATE INDEX ix_show_skipped ON public.show USING btree (skipped);
CREATE INDEX ix_subtitle_record_episode_id ON public.subtitle_record USING btree (episode_id);
CREATE INDEX ix_subtitle_record_episode_language ON public.subtitle_record USING btree (episode_id, language);
CREATE INDEX ix_subtitle_record_movie_id ON public.subtitle_record USING btree (movie_id);
CREATE INDEX ix_subtitle_record_movie_language ON public.subtitle_record USING btree (movie_id, language);
CREATE INDEX ix_torrent_created_at_desc ON public.torrent USING btree (created_at DESC);
CREATE INDEX ix_torrent_created_at_id_desc ON public.torrent USING btree (created_at DESC, id DESC);
CREATE INDEX ix_torrent_history_imported_at_desc ON public.torrent_history USING btree (imported_at DESC);
CREATE INDEX ix_torrent_history_outcome ON public.torrent_history USING btree (outcome);
CREATE INDEX ix_torrent_status ON public.torrent USING btree (status);
CREATE INDEX ix_torrent_status_active ON public.torrent USING btree (status) WHERE (status <> 'finished'::public.torrentstatus);
CREATE UNIQUE INDEX ix_user_api_tokens_token_hash ON public.user_api_tokens USING btree (token_hash);
CREATE INDEX ix_user_api_tokens_user_id ON public.user_api_tokens USING btree (user_id);
CREATE UNIQUE INDEX ix_user_email ON public."user" USING btree (email);
CREATE UNIQUE INDEX uq_torrent_history_info_hash ON public.torrent_history USING btree (info_hash) WHERE (info_hash IS NOT NULL);
ALTER TABLE ONLY public.episode_file
    ADD CONSTRAINT episode_file_episode_id_fkey FOREIGN KEY (episode_id) REFERENCES public.episode(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.episode_file
    ADD CONSTRAINT episode_file_torrent_id_fkey FOREIGN KEY (torrent_id) REFERENCES public.torrent(id) ON DELETE SET NULL;
ALTER TABLE ONLY public.episode
    ADD CONSTRAINT episode_season_id_fkey FOREIGN KEY (season_id) REFERENCES public.season(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.media_request
    ADD CONSTRAINT media_request_decided_by_id_fkey FOREIGN KEY (decided_by_id) REFERENCES public."user"(id) ON DELETE SET NULL;
ALTER TABLE ONLY public.media_request
    ADD CONSTRAINT media_request_movie_id_fkey FOREIGN KEY (movie_id) REFERENCES public.movie(id) ON DELETE SET NULL;
ALTER TABLE ONLY public.media_request
    ADD CONSTRAINT media_request_requested_by_id_fkey FOREIGN KEY (requested_by_id) REFERENCES public."user"(id) ON DELETE SET NULL;
ALTER TABLE ONLY public.media_request
    ADD CONSTRAINT media_request_show_id_fkey FOREIGN KEY (show_id) REFERENCES public.show(id) ON DELETE SET NULL;
ALTER TABLE ONLY public.movie_file
    ADD CONSTRAINT movie_file_movie_id_fkey FOREIGN KEY (movie_id) REFERENCES public.movie(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.movie_file
    ADD CONSTRAINT movie_file_torrent_id_fkey FOREIGN KEY (torrent_id) REFERENCES public.torrent(id) ON DELETE SET NULL;
ALTER TABLE ONLY public.oauth_account
    ADD CONSTRAINT oauth_account_user_id_fkey FOREIGN KEY (user_id) REFERENCES public."user"(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.season
    ADD CONSTRAINT season_show_id_fkey FOREIGN KEY (show_id) REFERENCES public.show(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.subtitle_record
    ADD CONSTRAINT subtitle_record_episode_id_fkey FOREIGN KEY (episode_id) REFERENCES public.episode(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.subtitle_record
    ADD CONSTRAINT subtitle_record_movie_id_fkey FOREIGN KEY (movie_id) REFERENCES public.movie(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.user_api_tokens
    ADD CONSTRAINT user_api_tokens_user_id_fkey FOREIGN KEY (user_id) REFERENCES public."user"(id) ON DELETE CASCADE;

"""


def upgrade() -> None:
    for statement in (s.strip() for s in SCHEMA_SQL.split(";")):
        if statement:
            op.execute(statement)


def downgrade() -> None:
    # Safe contract: refuse downgrade below the base revision. The squashed
    # initial schema cannot enumerate every MiraMedia-owned object reliably,
    # and the previous implementation dropped all of public (including
    # unrelated tables, extensions, and grants). The supported migration floor
    # is this revision; use a disposable database or restore from backup.
    msg = (
        "Refusing to downgrade below the base migration revision "
        f"{revision}. Reversing the initial schema would require dropping the "
        "entire public schema, which may delete unrelated database objects. "
        "The supported migration floor is this revision; recreate a disposable "
        "database or restore from backup instead of downgrading further."
    )
    raise RuntimeError(msg)
