"use client";

import { ApiReferenceReact } from "@scalar/api-reference-react";
import "@scalar/api-reference-react/style.css";
import { useTheme } from "next-themes";

/**
 * Live, interactive Scalar API reference.
 *
 * Schema is fetched at runtime from the running backend so it always matches
 * the deployed instance (including config-gated endpoints). The bundle is
 * shipped in the static export — no CDN, works offline. Dark mode follows the
 * site theme.
 *
 * On the GitHub Pages docs site there is no backend to serve `/openapi.json`,
 * so the docs build sets NEXT_PUBLIC_OPENAPI_URL to a static spec bundled in
 * the export (web/public/openapi.json, regenerated by `make openapi`).
 */
export default function ApiReference() {
  const { resolvedTheme } = useTheme();
  // Same base the rest of the SPA uses; empty string = same-origin (prod),
  // honors BASE_PATH/NEXT_PUBLIC_API_URL exactly like the api client.
  const base = process.env.NEXT_PUBLIC_API_URL || "";
  // Explicit override (set by the Pages docs build) wins; otherwise fetch the
  // live spec from the backend so it matches the deployed instance.
  const specUrl = process.env.NEXT_PUBLIC_OPENAPI_URL || `${base}/openapi.json`;

  return (
    <ApiReferenceReact
      configuration={{
        url: specUrl,
        darkMode: resolvedTheme === "dark",
        hideDarkModeToggle: true,
        // Disable the Scalar "Ask AI" agent chat (on by default on localhost).
        agent: { disabled: true },
      }}
    />
  );
}
